apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      targetPort: 9090
      name: web-server
    - port: 9000
      targetPort: 
      name: s3-server
# clusterIP: #if you wanna specify a fixed clusterIP for the service
  type: ClusterIP
