apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
stringData:
  MINIO_ACCESS_KEY: "minio"    # DEFAULT VALUE, TYPE YOUR DESIRED LOGIN HERE
  MINIO_SECRET_KEY: "password" # DEFAULT VALUE, TYPE YOUR PASSWORD HERE
type: Opaque