apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
data:
  MINIO_ACCESS_KEY: bWluaW8K      # base64 of the DEFAULT VALUE "minio", TYPE YOUR DESIRED LOGIN HERE
  MINIO_SECRET_KEY: cGFzc3dvcmQK  # base64 of the DEFAULT VALUE "password", TYPE YOUR PASSWORD HERE
type: Opaque

# The same effect of this file can be achieved running the following command in your cluster:

# kubectl -n minio create secret generic minio-credentials --from-literal=MINIO_ACCESS_KEY=minio --from-literal=MINIO_SECRET_KEY=password

# Keep in mind that base64 is not hashing, and it can be decoded, there are better ways to manage k8s secrets !!!